### PR TITLE
Rebase to the latest version of AsciiMathML

### PR DESCRIPTION
**Pull request by LexSong**
I add the patch of `\matrix` as your recommendation. Please take a look

### CODE REVIEW

**Comment by LexSong** [comment]
Rebasing seems to mess up the order of commits on Github. I hope it still works fine.

See also https://github.com/asciimath/asciimathml/pull/90

**Comment by LexSong** [comment]
Rebase to e264b972cde776a6c73eaeb25e0c32d65c722bfc, fix #90

**Comment by yuwash** [comment]
Thanks a lot for your work! I'll test ASAP. Excuse me for the delay.

**Comment by LexSong** [comment]
No problem, thanks for your original work. It saves me a lot of trouble.

**Comment by yuwash** [comment]
It works as far as my example matrices are concerned, so I merged. I’m happy to hear you enjoyed using this!

**Pull request merged**
